### PR TITLE
package.go: pick null or en language

### PR DESCRIPTION
**Pull request by xgqt**
Signed-off-by: Maciej Barć <xgqt@gentoo.org>

### CODE REVIEW

**Comment by xgqt** [comment]
No idea if it works since docker-compose errors for me

image

**Comment by thesamesam** [comment]
cc @antarus12345 @arzano

**Comment by antarus12345** [comment]
This is merged.

**Comment by antarus12345** [comment]
https://gitweb.gentoo.org/sites/soko.git/commit/pkg/portage/repository/package.go?id=f3e75bde64e7f3f1e068ac446b39ad89317d692a

**Comment by xgqt** [comment]
> https://gitweb.gentoo.org/sites/soko.git/commit/pkg/portage/repository/package.go?id=f3e75bde64e7f3f1e068ac446b39ad89317d692a

Thanks!

**Pull request closed without merging**
