### PR TITLE
repo../mask.go: add slot and subslot condition when update

### PR DESCRIPTION
**Pull request by bekcpear**
this commit fix bug: https://bugs.gentoo.org/832042

Signed-off-by: bekcpear <i@bitbili.net>

### CODE REVIEW

**Comment by thesamesam** [comment]
cc @antarus12345 @arzano

**Comment by antarus12345** [comment]
I'll try to budget time to review this tonight; I'm a little miffed I never made @arzano write more tests...its kind of annoying that we can't share this code between languages :(

@radhermit any thoughts on code sharing (can we parse this with rust and FFI?)

**Comment by radhermit** [comment]
> @radhermit any thoughts on code sharing (can we parse this with rust and FFI?)

Yes, it wouldn't be that difficult, but then you'd start depending on some pkgcraft crate. For that to be more sane, it would probably be nice to split up the core library into various pieces since building it now will pull in the whole core stack meaning you'd get embedded bash as well. :laughing: 

Anyway, I already opened an issue for go bindings some time ago (https://github.com/pkgcraft/pkgcraft/issues/38) but I haven't looked into it yet.

**Comment by arthurzam** [comment]
I've taken the implementation, improved the code, optimized a lot and updated the code to the updated code base. Thank you for the PR!

**Pull request closed without merging**
